#include "ofApp.h"

/*

	OpenFrameworks ofxNDI audio example

	Demonstrates sending audio together with graphics

	Read from an audio file using MiniAudio
	https://miniaud.io

	NDI SDK
	https://ndi.video

	Copyright (C) 2026 Lynn Jarvis.
	https://github.com/leadedge/ofxNDI
	http://www.spout.zeal.co

	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	
*/

//--------------------------------------------------------------
void ofApp::setup()
{

	ofBackground(0);

	//
	// Load an audio file.
	// MiniAudio is used to read the file audio data.
	// Audio files are typically 44100 sample rate
	//
	// 48000 hz audio
	// https://freemusicarchive.org/music/Scott_Gratton/progress-and-regress/all-the-time-you-never-had-1/
	// std::string inputAudio = ofToDataPath("Scott Gratton - All the Time You Never Had.mp3", true);
	//
	// 44100 hz audio
	// https://freemusicarchive.org/music/Chad_Crouch/arps-ii/systems/
	std::string inputAudio = ofToDataPath("Chad Crouch - Systems.mp3", true);

	// NDI video frame rate
	// Video at 29.97 fps requires a sequence for the audio sample number per frame
	// This is generated by "ofxNDIutils::AudioFrameSequence"
	videoFps = 29.97;
	ndiSender.SetFrameRate(videoFps);

    // Audio file full path
	if (inputAudio.empty()) {
		ndiSender.SetAudio(false);
	}
	else {
		// Initialize the miniaudio decoder for 32-bit floating point audio
		// Floating point data is required by NDI
		//   inputAudio is the audio file path
		//   audioformat, nChannels, sampleRate are returned
		int audioformat = 0;
		if (audiofile.InitializeDecoder(inputAudio, audioformat, nChannels, sampleRate)) {
			//
			// The Audio/Video rate is not necessarily a whole number.
			//
			// The audio file sample rate and video fps are used to calculate a sequence
			// For example, 48000hz audio requires 1601.6 samples per frame at 29.97 fps.
			//   1602, 1601, 1602, 1601, 1602
			// and 44100 requires 1471.470
			//   1472, 1471, 1472, 1471, 1471,
			// A sequence length of 5 is usually sufficient
			//
			int samplemax = 0; // Maximum sample number for buffer allocation
			audiosamples = ofxNDIutils::AudioFrameSequence(sampleRate, ndiSender.GetFrameRate(), samplemax, 5);
			if (!audiosamples.empty()) {

				// Set to use audio
				ndiSender.SetAudio(true);

				// Use the audio file decoder sample rate and number of channels
				ndiSender.SetAudioSampleRate(sampleRate);
				ndiSender.SetAudioChannels(nChannels);

				// Set the number of samples per frame
				// This is changed every frame according to the sample sequence
				ndiSender.SetAudioSamples(samplemax);

				// Allocate for the maximum sample number in the sequence
				float* p_data = (float*)malloc(samplemax * nChannels * sizeof(float));
				ndiSender.SetAudioData(p_data);

				//
				// MiniAudio returns interleaved 32 bit float data.
				// Set the audio type so that this data is sent using :
				//    "NDIlib_audio_frame_interleaved_32f_t"
				//
				ndiSender.SetAudioType(audio_frame_interleaved_32f_t);
			}
		}
		else {
			printf("MiniAudio could not decode the audio file\n");
		}
	}

	// NDI sender name
	senderName = "ofxNDI audio file sender";
	ofSetWindowTitle(senderName); // show it on the title bar

	// NDI sender image dimensions
	senderWidth  =  1280;
	senderHeight =   720;

	// Allocate an RGBA fbo for texture draw
	m_fbo.allocate(senderWidth, senderHeight, GL_RGBA);

	// Create an NDI sender with YUV image output format
	ndiSender.SetFormat(NDIlib_FourCC_video_type_UYVY);
	bInitialized = ndiSender.CreateSender(senderName.c_str(), senderWidth, senderHeight);
	if(bInitialized)
		printf("Created sender [%s]\n", senderName.c_str());
	else
		printf("CreateSender failed\n");

	// 3D drawing setup for the demo graphics
	glEnable(GL_DEPTH_TEST); // enable depth comparisons and update the depth buffer
	glHint(GL_PERSPECTIVE_CORRECTION_HINT, GL_NICEST); // Really Nice Perspective Calculations
	ofDisableAlphaBlending(); // To prevent trails with the rotating cube
	// ofDisableArbTex is needed to create a texture with
	// normalized coordinates for bind in DrawGraphics
	ofDisableArbTex();
	textureImage.load("SpoutBox.jpg");
	ofEnableArbTex(); // Back to default pixel coordinates

}

//--------------------------------------------------------------
void ofApp::update()
{

}

//--------------------------------------------------------------
void ofApp::draw()
{
	ofBackground(10, 100, 140, 255);
	ofSetColor(255);

	// Check success of CreateSender
	if (!bInitialized)
		return;

	// Send audio
	if (!audiosamples.empty()) {

		// Read data from the audio file using MiniAudio

		// Set the number of audio samples to read for this frame
		// based on the audio sample number sequence and it's size
		nSamples = audiosamples[audioindex % (int)audiosamples.size()];
		ndiSender.SetAudioSamples(nSamples);
		audioindex++;
		// Reset the index if it exceeds the sample size
		if (audioindex > (int)audiosamples.size())
			audioindex = 0;

		// Read the next lot of audio frames from the file
		// GetAudioData() is a pointer to allocated float audio frame data
		float* audiodata = ndiSender.GetAudioData();
		audiofile.ReadAudioFrames(audiodata, nSamples);

		// Set new audio data to the sender audio frame
		ndiSender.SetAudioData(audiodata);

		// Send the audio data
		ndiSender.NDIsender.SendAudio();
		
	}

	// Draw graphics to an fbo and display it
	DrawGraphics();

	// Send the graphics image
	ndiSender.SendImage(m_fbo);

	// Draw the audio waveform
	DrawAudio();

}

void ofApp::DrawGraphics()
{
	// Draw graphics into an fbo used for the examples
	m_fbo.begin();
	ofEnableDepthTest();
	ofClear(10, 100, 140, 255);
	ofPushMatrix();
	ofTranslate((float)senderWidth / 2.0, (float)senderHeight / 2.0, 0);
	ofRotateYDeg(rotX);
	ofRotateXDeg(rotY);
	textureImage.getTexture().bind();
	ofDrawBox(0.4*(float)senderHeight);
	textureImage.getTexture().unbind();
	ofPopMatrix();
	ofDisableDepthTest();
	m_fbo.end();

	// Draw the fbo result fitted to the display window
	m_fbo.draw(0, 0, ofGetWidth(), ofGetHeight());

	// Rotate the cube (30 fps)
	rotX += 1.5;
	rotY += 1.5;

}

void ofApp::DrawAudio()
{

	if (!ndiSender.GetAudio() || !ndiSender.GetAudioData())
		return;

	//
	// The audio type is set to 32 bit interleaved
	// (SetAudioType(audio_frame_interleaved_32f_t))
	// Assign left and right vectors for interleaved
	//   L R L R L R L R L R L R L R L R ...
	//

	// Left channel
	float* audiodata = ndiSender.GetAudioData();
	lAudio.assign(audiodata, audiodata+nSamples*2);

	// Right channel - assign starting at the second sample
	audiodata++; 
	rAudio.assign(audiodata, audiodata+nSamples*2);

	//
	// Calculate volume (interleaved audio data)
	//
	float leftVol = 0.0f;
	float rightVol = 0.0f;
	float count = 0.0f;
	for (int i=0; i < nSamples*2; i+=2) { // Every second sample
		leftVol  += lAudio[i]*lAudio[i];
		rightVol += rAudio[i]*rAudio[i];
		count++;
	}
	leftVol  = sqrt(leftVol/count);  // left rms
	rightVol = sqrt(rightVol/count); // right rms

	//
	// DB bar graph
	//

	//
	// Left channel
	//
	// Clamp rms values to avoid log 0 and convert rms to db
	float dB = 20.0f*log10(ofClamp(leftVol, 0.000001f, 1.0f));
	// map to 2/3 window height
	float mapDB = ofMap(dB, -60, 0, 0, ofGetHeight()*2/3, true);
	drawGradientBar(10, ofGetHeight()-mapDB, 7, mapDB);
	//
	// Right channel
	//
	dB = 20.0f*log10(ofClamp(rightVol, 0.000001f, 1.0f));
	mapDB = ofMap(dB, -60, 0, 0, ofGetHeight()*2/3, true);
	drawGradientBar(20, ofGetHeight()-mapDB, 7, mapDB);

	//
	// Audio waveform graph
	//

	// Audio data is -1.0 - +1.0
	// increase to +- 1/3 window height
	float height = (float)(ofGetHeight()/3);
	float ypos = 0.0f;
	float lasty = ypos;
	float xpos = 0.0f;
	float lastx = xpos;

	// nSamples includes left and right channel data
	// nSamples/2 spaced over the window width
	float spacing = (float)ofGetWidth()/(float)nSamples/2;
	float y = (float)(ofGetHeight()/2); // Centre of the window
	for (int i=0; i < nSamples*2; i+=2) { // Every second sample
		xpos = (float)i*spacing;
		// Average of left and right channels
		ypos = y + ((lAudio[i]*height) + (rAudio[i]*height))/2;
		if (xpos > lastx) ofDrawLine(lastx, lasty, xpos, ypos);
		lastx = xpos;
		lasty = ypos;
	}

}

// Similar to Studio Monitor
void ofApp::drawGradientBar(float x, float y, float width, float height)
{
    ofMesh mesh;
    mesh.setMode(OF_PRIMITIVE_TRIANGLE_STRIP);

    // Bottom color (Blue)
    mesh.addVertex(glm::vec3(x, y+height, 0));
	mesh.addColor(ofColor(0, 64, 255));

    mesh.addVertex(glm::vec3(x+width, y+height, 0));
	mesh.addColor(ofColor(0, 64, 255));

    // Middle color (Green)
    float midY = y+height*0.10f;

    mesh.addVertex(glm::vec3(x, midY, 0));
	mesh.addColor(ofColor(0, 225, 0));

    mesh.addVertex(glm::vec3(x+width, midY, 0));
	mesh.addColor(ofColor(0, 225, 0));

    mesh.draw();
}

//--------------------------------------------------------------
void ofApp::exit()
{
	// Release the sender or NDI sender discovery will still find it
	// This also releases the audio data buffer
	ndiSender.ReleaseSender();
}
